name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # Or the branch you want to sync

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install

    - name: Sync with Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: git push https://SSenti:$HF_TOKEN@huggingface.co/spaces/SSenti/yt_summ main

